-- =======================================================
-- ORACLE DATABASE SCHEMA: ATTENDANCE MANAGEMENT SYSTEM
-- Project: Oracle COE Academic Project
-- =======================================================

-- Drop existing tables (with cascade constraints) to allow clean re-runs
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE attendance_summary CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE attendance CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE student_subject CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE subject CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE faculty CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE student CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- -------------------------------------------------------
-- 1. STUDENT TABLE
-- -------------------------------------------------------
CREATE TABLE student (
    student_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student_name    VARCHAR2(100) NOT NULL,
    email           VARCHAR2(100) NOT NULL CONSTRAINT uq_student_email UNIQUE,
    password        VARCHAR2(100) NOT NULL,
    department      VARCHAR2(50)  NOT NULL,
    year_of_study   NUMBER(1)     NOT NULL CONSTRAINT chk_student_year CHECK (year_of_study BETWEEN 1 AND 4),
    section         VARCHAR2(10)  NOT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- -------------------------------------------------------
-- 2. FACULTY TABLE
-- -------------------------------------------------------
CREATE TABLE faculty (
    faculty_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    faculty_name    VARCHAR2(100) NOT NULL,
    email           VARCHAR2(100) NOT NULL CONSTRAINT uq_faculty_email UNIQUE,
    password        VARCHAR2(100) NOT NULL,
    department      VARCHAR2(50)  NOT NULL
);

-- -------------------------------------------------------
-- 3. SUBJECT TABLE
-- -------------------------------------------------------
CREATE TABLE subject (
    subject_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subject_code    VARCHAR2(20)  NOT NULL CONSTRAINT uq_subject_code UNIQUE,
    subject_name    VARCHAR2(100) NOT NULL,
    department      VARCHAR2(50)  NOT NULL,
    year_of_study   NUMBER(1)     NOT NULL CONSTRAINT chk_subject_year CHECK (year_of_study BETWEEN 1 AND 4),
    semester        NUMBER(1)     NOT NULL CONSTRAINT chk_subject_sem CHECK (semester BETWEEN 1 AND 8)
);

-- -------------------------------------------------------
-- 4. STUDENT_SUBJECT TABLE (Many-to-Many mapping)
-- -------------------------------------------------------
CREATE TABLE student_subject (
    student_id      NUMBER NOT NULL,
    subject_id      NUMBER NOT NULL,
    CONSTRAINT pk_student_subject PRIMARY KEY (student_id, subject_id),
    CONSTRAINT fk_ss_student FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE,
    CONSTRAINT fk_ss_subject FOREIGN KEY (subject_id) REFERENCES subject(subject_id) ON DELETE CASCADE
);

-- -------------------------------------------------------
-- 5. ATTENDANCE TABLE
-- -------------------------------------------------------
CREATE TABLE attendance (
    attendance_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student_id      NUMBER NOT NULL,
    subject_id      NUMBER NOT NULL,
    attendance_date DATE NOT NULL,
    status          VARCHAR2(10) NOT NULL CONSTRAINT chk_attendance_status CHECK (status IN ('PRESENT', 'ABSENT')),
    marked_by       NUMBER,
    CONSTRAINT fk_att_student FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE,
    CONSTRAINT fk_att_subject FOREIGN KEY (subject_id) REFERENCES subject(subject_id) ON DELETE CASCADE,
    CONSTRAINT fk_att_faculty FOREIGN KEY (marked_by)  REFERENCES faculty(faculty_id) ON DELETE SET NULL,
    -- Prevent duplicate attendance for the same student, subject, and date
    CONSTRAINT uq_student_subject_date UNIQUE (student_id, subject_id, attendance_date)
);

-- -------------------------------------------------------
-- 6. ATTENDANCE_SUMMARY TABLE
-- -------------------------------------------------------
CREATE TABLE attendance_summary (
    summary_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student_id            NUMBER NOT NULL,
    subject_id            NUMBER NOT NULL,
    total_classes         NUMBER DEFAULT 0 NOT NULL,
    present_count         NUMBER DEFAULT 0 NOT NULL,
    absent_count          NUMBER DEFAULT 0 NOT NULL,
    attendance_percentage NUMBER(5, 2) DEFAULT 0 NOT NULL CONSTRAINT chk_att_summary_pct CHECK (attendance_percentage BETWEEN 0 AND 100),
    last_calculated       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_summary_student FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE,
    CONSTRAINT fk_summary_subject FOREIGN KEY (subject_id) REFERENCES subject(subject_id) ON DELETE CASCADE,
    CONSTRAINT uq_summary_student_subject UNIQUE (student_id, subject_id)
);

-- Create performance indexes for common lookups and foreign keys
CREATE INDEX idx_att_student ON attendance(student_id);
CREATE INDEX idx_att_subject ON attendance(subject_id);
CREATE INDEX idx_att_date ON attendance(attendance_date);
CREATE INDEX idx_att_student_subject ON attendance(student_id, subject_id);
